// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8YPYvcqV6g36X0s938oz1D-Fy15dlzqk',
    appId: '1:1066131039124:web:620d84bb784aa5c64e2581',
    messagingSenderId: '1066131039124',
    projectId: 'soulsphere-f2e7f',
    authDomain: 'soulsphere-f2e7f.firebaseapp.com',
    storageBucket: 'soulsphere-f2e7f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7DWHBs_G4uPPBMeh1UmSdIoZSGhCwbRc',
    appId: '1:1066131039124:android:4e458f146ae38ce94e2581',
    messagingSenderId: '1066131039124',
    projectId: 'soulsphere-f2e7f',
    storageBucket: 'soulsphere-f2e7f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDb_r--PNZXSsix0D-084ddnY6_X3mgER0',
    appId: '1:1066131039124:ios:f9a69ee6c9e488b64e2581',
    messagingSenderId: '1066131039124',
    projectId: 'soulsphere-f2e7f',
    storageBucket: 'soulsphere-f2e7f.appspot.com',
    iosBundleId: 'com.example.soulSphere',
  );

}